# Site settings
title: Ronan Costello
email: rcostello@live.ie
description: > # this means to ignore newlines until "baseurl:"
  Hello! I’m Ronan - a UX designer, a UI designer and a general maker of stuff living in Limerick, Ireland.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "ronancostello.com" # the base hostname & protocol for your site
twitter_username: anonymousronan
github_username:  anonymousronan

# Build settings
markdown: kramdown
